### ISSUE TITLE
Unicode support feasibility 

### ISSUE THREAD

**Issue by lifeofdave** [rsgalloway/pyseq#21]
How much work would it entail to add Unicode support to pyseq? If it's feasible I'm happy to contribute..

**Comment by rsgalloway** [comment]
That's an interesting question. Are you asking because you want to support multiple languages? I think as long as the numerals are parsable then there's no reason it should not work. Have you tested it?

Here's a quick parse test I did just copy/pasting some Tibetan and adding "1000" to the string to see if it could be parsed:

```
>>> i = pyseq.Item("ༀ ༁ ༂ ༃.1000. ༅ ༆ ༇ ༈ ༉ ༊")
>>> i.digits
['1000']
```

**Comment by rsgalloway** [comment]
Hi, have you tried this yet? Did it work for you? I'd like to know if I can close this, thanks.

**Comment by broganross** [comment]
I think 22560e003dd475de61a82126805a147255e9b76a fixed the issue in 'get_sequences'.  But i haven't tested special characters.  And that's in 0.5.1, which would be nice to get a build of.

**Comment by rsgalloway** [comment]
Yeah, it works for me, just wanted to double check. Closing this out for now.
