### ISSUE TITLE
Sequence member operations

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/pyseq#6]
Ability to operate on members of a Sequence, e.g.
- rename/move: mv the file on disk (may change membership)
- reindex: change the frame number of one or more Items
- copy: cp one or more Items to a specified path
- exists: return True of the Item exists on disk
- delete: rm one or more Items

To operate on all members, the method should be called from the Sequence class level. To operate on a subset of members or a single Item, the method should eb called on the Item.

**Comment by broganross** [comment]
As far as move and copy there's a couple different ways to go.  It could be simple, like move/copy the sequence to a new directory.  User gives a directory and optionally the start and end indexes.

Or you could use the formatting stuff to define a new location and file name.

You could also add md5 checksums as an option so that cross storage transfers are validated.

The only problem with giving the functionality to items as well is if the user Item.moves, but doesn't pop it from the Sequence.  Which could be worked around by each Item storing a reference to it's Sequence.  But even weakrefs seems a little over kill to me.

**Comment by broganross** [comment]
I was thinking about this and I might have a decent solution

move( to_dir=None, to_name=None, frame_range=None, offset=0, md5=False):

You need to either give to_dir, to_name, or offset.  Or any combination of the three.
Frame range is a (%r) formatted string of the frame range that will be moved.
Offset is the optional reframing integer, based on either the first frame in frame_range, or the sequence's first frame.
Md5 will make the method do a copy, creating a md5 checksum, and validate the destination file's md5 before removing the source.

I think the return value should always be a sequence, and it's up to the user to know whether it's a new partial one or not.  If they ask to move the first 50 frames of Seq(1-100), they get Seq(1-50) back.  If they move all 100 frames they get a new Seq(1-100)

**Comment by rsgalloway** [comment]
changing this to "wontfix", to keep thing light and since things like this can be deceptively simple, let's leave operations to clients.
